# Generated by Django 5.2.17 on 2026-09-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'managed': False},
        ),
    ]
