# Generated by Django 5.2.17 on 2026-09-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProfesional',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'areaprofesional',
            },
        ),
        migrations.CreateModel(
            name='EstadoPostulacion',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estadopostulacion',
            },
        ),
        migrations.CreateModel(
            name='ModalidadTrabajo',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'modalidadtrabajo',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rolusuario',
            },
        ),
    ]
