# Generated by Django 5.2.17 on 2026-09-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('passwordHash', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fechaRegistro', models.DateField(blank=True, null=True)),
                ('rol', models.ForeignKey(blank=True, db_column='rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rolusuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
