# Generated by Django 5.2.17 on 2026-09-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('nivelAcceso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidato',
            },
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('emailCorporativo', models.EmailField(blank=True, max_length=100, null=True)),
                ('verificado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleador',
            },
        ),
    ]
