# Generated by Django 5.2.17 on 2026-09-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_administrador_candidato_empleador'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeVida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urlArchivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaCarga', models.DateField(blank=True, null=True)),
                ('tamanoMB', models.FloatField(blank=True, null=True)),
                ('candidato', models.OneToOneField(blank=True, db_column='candidato_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.candidato')),
            ],
            options={
                'db_table': 'hojadevida',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaEnvio', models.DateField(blank=True, null=True)),
                ('enviada', models.BooleanField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobada', models.BooleanField(blank=True, null=True)),
                ('fechaPublicacion', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.areaprofesional')),
                ('empleador', models.ForeignKey(blank=True, db_column='empleador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleador')),
                ('modalidad', models.ForeignKey(blank=True, db_column='modalidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modalidadtrabajo')),
            ],
            options={
                'db_table': 'ofertalaboral',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPostulacion', models.DateField(blank=True, null=True)),
                ('candidato', models.ForeignKey(blank=True, db_column='candidato_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.candidato')),
                ('estado', models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estadopostulacion')),
                ('oferta', models.ForeignKey(blank=True, db_column='oferta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ofertalaboral')),
            ],
            options={
                'db_table': 'postulacion',
            },
        ),
    ]
