# Generated by Django 5.2.17 on 2026-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPostulacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('candidato_id', models.IntegerField(blank=True, null=True)),
                ('oferta_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postulacion',
                'managed': False,
            },
        ),
    ]
