# Generated by Django 5.2.17 on 2026-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeVida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urlArchivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaCarga', models.DateField(blank=True, null=True)),
                ('tamanoMB', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hojadevida',
                'managed': False,
            },
        ),
    ]
