# Generated by Django 5.2.17 on 2026-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rolusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('passwordHash', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fechaRegistro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
