# Generated by Django 5.2.17 on 2026-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=30, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('aprobada', models.BooleanField(blank=True, null=True)),
                ('fechaPublicacion', models.DateField(blank=True, null=True)),
                ('empleador_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofertalaboral',
                'managed': False,
            },
        ),
    ]
